apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: lakehouse
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: api
    nodePort: 30900
  - port: 9001
    targetPort: 9001
    name: console
    nodePort: 30901
