apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: lakehouse
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
  - port: 7077
    targetPort: 7077
    name: spark
    nodePort: 30077
  - port: 8080
    targetPort: 8080
    name: ui
    nodePort: 30080
