apiVersion: v1
kind: Service
metadata:
  name: spark-notebook
  namespace: lakehouse
spec:
  type: NodePort
  selector:
    app: spark-notebook
  ports:
  - port: 8888
    targetPort: 8888
    name: notebook
    nodePort: 30888
  - port: 4040
    targetPort: 4040
    name: spark-ui
