apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
  labels:
    app: notebook
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dcscience/data-lakehouse-k8s/workspace"
