apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: sk97/spark-master-custom:latest
        imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 7077
        - containerPort: 8080
        volumeMounts:
        - name: spark-defaults
          mountPath: /opt/spark/conf
      volumes:
      - name: spark-defaults
        configMap:
          name: spark-master-config
